//
// Created by mx on 01/07/2017.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ml_tech_mx_mlservice_MlMotor */

#ifndef _Included_cn_ml_tech_mx_mlservice_MlMotor
#define _Included_cn_ml_tech_mx_mlservice_MlMotor
#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <sys/ioctl.h>

#include <string.h>
#include <android/log.h>
#include <jni.h>
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>



/*寄存器数据结构*/
struct reg_val
{
    uint32_t reg;//寄存器地址
    uint32_t  val;//寄存器数据
};

typedef struct _TINY_MOTOR
{
    uint8_t  num;     //电机号
    uint8_t  dir;       //电机方向

    uint16_t speed;       //电机速度
    uint16_t acc_time;      //加速时间
    uint16_t u16WaveNum;      //added by XuXiang 2015.10.12
}TINY_MOTOR;

typedef struct REPORT_DATA  //added by XuXiang 2015.5.5
{
    union
    {
        struct reg_val  motorReg;
        struct
        {
            uint8_t u8MotorState[8];
        };
        struct _TINY_MOTOR tinyMotor;
    }MOTOR;
    uint8_t dataType; //  1**:返回寄存器值(100 or 108:8位寄存器,116:16位寄存器，132：32位寄存器)  1：返回电机状>态
}Report_Data;

#define MOTOR_IOC_MAGIC   'x'

#define MOTORCMD_MOTOR_CONTROL _IOWR(MOTOR_IOC_MAGIC,4,Report_Data)

#define  LOG_TAG    "native-motor"
#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...)  __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)
#define LOGI(...)  __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
int fid = -1;
/*
 * Class:     cn_ml_tech_mx_mlservice_MlMotor
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_ml_1tech_mx_mlservice_MlMotor_getCLanguageString
        (JNIEnv *env, jclass obj) {
    return (*env)->NewStringUTF(env, "This just a test for Android Studio NDK JNI developer!");
}

/*
 * Class:     cn_ml_tech_mx_mlservice_MlMotor
 * Method:    initMotor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_ml_1tech_mx_mlservice_MlMotor_initMotor
        (JNIEnv *env, jclass obj) {
    int fd = -1;
    fd = open("/dev/motor_control", O_RDWR);
    LOGI("open fd = %d\n", fd);
    fid = fd;
    return fd;
}

/*
 * Class:     cn_ml_tech_mx_mlservice_MlMotor
 * Method:    uninitMotor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_ml_1tech_mx_mlservice_MlMotor_uninitMotor
        (JNIEnv *env, jclass obj, jint fd) {
    if (fd != -1) {
        close(fd);
    }
}

void Display_ReportData_motor(Report_Data *report_data) {
    LOGI("%d, %d, %d, %d, %d, %d\n", report_data->MOTOR.tinyMotor.num,
         report_data->MOTOR.tinyMotor.dir,
         report_data->MOTOR.tinyMotor.speed,
         report_data->MOTOR.tinyMotor.acc_time,
         report_data->MOTOR.tinyMotor.u16WaveNum,
         report_data->dataType);
}
/*
 * Class:     cn_ml_tech_mx_mlservice_MlMotor
 * Method:    motorControl
 * Signature: (Lcn/ml_tech/mx/mlservice/MlMotor/ReportDataVal;)V
 */
JNIEXPORT void JNICALL Java_cn_ml_1tech_mx_mlservice_MlMotor_motorControl
        (JNIEnv *env, jclass obj, jobject obj_motor) {
    jclass motor_class = (*env)->GetObjectClass(env, obj_motor);
    if (motor_class == NULL) {
        LOGI("GetObjectClass failed\n");
    }
    jfieldID numFieldId = (*env)->GetFieldID(env, motor_class, "num", "I");
    jfieldID dirFieldId = (*env)->GetFieldID(env, motor_class, "dir", "I");
    jfieldID speedFieldId = (*env)->GetFieldID(env, motor_class, "speed", "I");
    jfieldID accTimeFieldId = (*env)->GetFieldID(env, motor_class, "acc_time", "I");
    jfieldID u16WaveNumFieldId = (*env)->GetFieldID(env, motor_class, "u16WaveNum", "I");
    jfieldID dataTypeFieldId = (*env)->GetFieldID(env, motor_class, "dataType", "I");
    Report_Data report_data;
    report_data.MOTOR.tinyMotor.dir = (*env)->GetIntField(env, obj_motor, dirFieldId);
    report_data.MOTOR.tinyMotor.speed = (*env)->GetIntField(env, obj_motor, speedFieldId);
    report_data.MOTOR.tinyMotor.acc_time = (*env)->GetIntField(env, obj_motor, accTimeFieldId);
    report_data.MOTOR.tinyMotor.u16WaveNum = (*env)->GetIntField(env, obj_motor, u16WaveNumFieldId);
    report_data.MOTOR.tinyMotor.num = (*env)->GetIntField(env, obj_motor, numFieldId);
    report_data.dataType = (*env)->GetIntField(env, obj_motor, dataTypeFieldId);
    Display_ReportData_motor(&report_data);
    ioctl(fid, MOTORCMD_MOTOR_CONTROL, &report_data);
}

#ifdef __cplusplus
}
#endif
#endif
