/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ml_tech_mx_mlservice_DialogUtils */

#ifndef _Included_cn_ml_tech_mx_mlservice_DialogUtils
#define _Included_cn_ml_tech_mx_mlservice_DialogUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ml_tech_mx_mlservice_DialogUtils
 * Method:    doCallBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_cn_ml_1tech_mx_mlservice_DialogUtils_doCallBack
(JNIEnv
* env ,
jobject obj
)
{
//回调Java中的方法

jclass cls = (*env)->GetObjectClass(env, obj);//获得Java类实例
jmethodID callbackID = (*env)->GetMethodID(env, cls, "callback",
                                           "(Ljava/lang/String;)V");//或得该回调方法句柄


jstring native_desc = (*env)->NewStringUTF(env, " I am Native");

(* env)->
CallVoidMethod(env, obj, callbackID, native_desc
); //回调该方法，并且传递参数值
}

#ifdef __cplusplus
}
#endif
#endif
